In [1]:
import numpy as np
import cv2

In [7]:
# butterfly = 'https://i.pinimg.com/originals/36/43/18/3643186bc7e37b00509ec352cf9b7bfc.jpg' 

In [3]:
# img = cv2.imread(filename)
# img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)

# DataTypes and Structure

In [4]:
img1 = np.zeros([150,200,1], 'uint8')
cv2.imshow("Black", img1)
print(img1[0,0,:])

img2 = np.ones([150,200,3], 'uint8')
cv2.imshow("Ones", img2)
print(img2[0,0,:])

white = np.ones([150,200,3], 'uint16') #16 bit line image
white *= (2**16 - 1)
cv2.imshow("White", white)
print(white[0,0,:])

color = img2.copy() #creating a deep copy of an image #two are not connected to each other at all
color[:,:] = (255,200,0) #BGR format all blue pixes
cv2.imshow("Blue", color)
print(color[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[0]
[1 1 1]
[65535 65535 65535]
[255 200   0]


# Image Types and Color Channels

In [3]:
color = cv2.imread("butterfly.jpg", 1)
cv2.imshow("Image", color)
cv2.moveWindow("Image",0,0)
print(color.shape)
height,width,channels = color.shape

b,g,r = cv2.split(color)

rgb_split = np.empty([height, width*3, 3], 'uint8')

rgb_split[:, 0:width] = cv2.merge([b,b,b])
rgb_split[:, width:width*2]= cv2.merge([g,g,g])
rgb_split[:, width*2:width*3]= cv2.merge([r,r,r])

cv2.imshow("Channels",rgb_split)
cv2.moveWindow("Channels",0,height)

hsv = cv2.cvtColor(color, cv2.COLOR_BGR2HSV)
h,s,v = cv2.split(hsv)
hsv_split = np.concatenate((h,s,v), axis=1)
cv2.imshow("Split hsv", hsv_split)

cv2.waitKey(0)
cv2.destroyAllWindows()

(412, 550, 3)


# Pixel Manupulation & Filtering

In [5]:
color = cv2.imread("butterfly.jpg", 1)

gray = cv2.cvtColor(color, cv2.COLOR_RGB2GRAY)
cv2.imwrite("gray.jpg", gray)

b = color[:,:,0]
g = color[:,:,1]
r = color[:,:,2]

rgba = cv2.merge((b,g,r,g)) #4th channel is to add transparancy layer
cv2.imwrite("rgba.png", rgba) #using png here as JPEG doesnot support image transparency 


True

# Gaussian Blur, Dilation & Erosion

In [3]:
# these filters can be combined and used together to remove the noise
image = cv2.imread("thresh.jpg")
cv2.imshow("Original", image)

blur = cv2.GaussianBlur(image, (5,55), 0)
cv2.imshow("Blur", blur)

kernel = np.ones((5,5), 'uint8') #finding the kernel

dilate = cv2.dilate(image, kernel, iterations=1)
erode = cv2.erode(image, kernel, iterations=1)

cv2.imshow("dilate", dilate)
cv2.imshow("erode", erode)

cv2.waitKey(0)
cv2.destroyAllWindows()

 # Scaling and Rotating

In [2]:
img = cv2.imread("players.jpg", 1)

# Scale
img_half = cv2.resize(img, (0,0), fx=0.5, fy=0.5)
img_stretch = cv2.resize(img, (600,600))
img_stretch_near = cv2.resize(img, (600,600), interpolation = cv2.INTER_NEAREST)

cv2.imshow("half", img_half)
cv2.imshow("stretch", img_stretch)
cv2.imshow("strech near", img_stretch_near)

#Rotation

M = cv2.getRotationMatrix2D((0,0), -30, 1)
rotated = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
cv2.imshow("rotated", rotated)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Video Inputs

In [1]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

#circle color and width
color = (0,255,0)
line_width = 3
radius = 100
point = (0,0)

def click(event, x, y, flags, param):
    global point, pressed
    if event == cv2.EVENT_LBUTTONDOWN:
        print("pressed", x, y)
        point = (x,y)
 
cv2.namedWindow("frame")
cv2.setMouseCallback("frame", click)

#0xFF only needed if you r using 64 but machine
while(True):
    ret, frame = cap.read()
    
    frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
    cv2.circle(frame, point, radius, color, line_width)
    cv2.imshow("frame",frame)
    
    ch = cv2.waitKey(1)
    if ch & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

pressed 332 156
pressed 351 256
pressed 339 199
pressed 339 192
pressed 335 203
pressed 505 88
pressed 180 126
pressed 155 221
pressed 117 310
pressed 453 266
pressed 521 230
pressed 321 221
